title: Syed Ashfaq # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Java Developer
  <br><br>
  Full Stack, Spring, Hibernate, Angular... 
  <br><br>
  <a href="https://www.linkedin.com/in/syedashfaq/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-163955090-1 # your Google Analytics tracking ID here
